my:
  name: forezp
  age: 12
  number:  ${random.int}
  uuid : ${random.uuid}
  max: ${random.int(10)}
  value: ${random.value}
  greeting: hi,i'm  ${my.name}
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true$characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 1234
server:
  port: 8080
  # 下面这个参数是为解决问题而新增的
  tomcat:
    max-http-header-size: 8192